version: 1
disable_existing_loggers: true



formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    error:
        format: "%%(asctime)s --- (levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:

    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    core_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: error
        filename: /tmp/core/core.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    dashboard_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: error
        filename: /tmp/dashboard/dashboard.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: standard
        filename: /tmp/core/critical.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    warn_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARN
        formatter: standard
        filename: /tmp/core/warn.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: NOTSET
    handlers: [console]
    propogate: yes

loggers:
    dashboard:
        level: INFO
        handlers: [console, dashboard_handler, critical_file_handler, warn_file_handler]
        propogate: no

    core:
        level: DEBUG
        handlers: [console, core_handler, critical_file_handler, warn_file_handler]
        propogate: yes
